In [1]:
import pandas as pd
import numpy as np

C:\Users\Biswajeet.Nayak\anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
C:\Users\Biswajeet.Nayak\anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)

In [2]:
data=pd.read_csv(r'D:\Datasets\Gramener\india-districts-census-2011.csv')
data.shape

(640, 118)

In [3]:
pd.options.display.max_columns=200

In [4]:
data.head()

,District code,State name,District name,Population,Male,Female,Literate,Male_Literate,Female_Literate,SC,Male_SC,Female_SC,ST,Male_ST,Female_ST,Workers,Male_Workers,Female_Workers,Main_Workers,Marginal_Workers,Non_Workers,Cultivator_Workers,Agricultural_Workers,Household_Workers,Other_Workers,Hindus,Muslims,Christians,Sikhs,Buddhists,Jains,Others_Religions,Religion_Not_Stated,LPG_or_PNG_Households,Housholds_with_Electric_Lighting,Households_with_Internet,Households_with_Computer,Rural_Households,Urban_Households,Households,Below_Primary_Education,Primary_Education,Middle_Education,Secondary_Education,Higher_Education,Graduate_Education,Other_Education,Literate_Education,Illiterate_Education,Total_Education,Age_Group_0_29,Age_Group_30_49,Age_Group_50,Age not stated,Households_with_Bicycle,Households_with_Car_Jeep_Van,Households_with_Radio_Transistor,Households_with_Scooter_Motorcycle_Moped,Households_with_Telephone_Mobile_Phone_Landline_only,Households_with_Telephone_Mobile_Phone_Mobile_only,Households_with_TV_Computer_Laptop_Telephone_mobile_phone_and_Scooter_Car,Households_with_Television,Households_with_Telephone_Mobile_Phone,Households_with_Telephone_Mobile_Phone_Both,Condition_of_occupied_census_houses_Dilapidated_Households,Households_with_separate_kitchen_Cooking_inside_house,Having_bathing_facility_Total_Households,Having_latrine_facility_within_the_premises_Total_Households,Ownership_Owned_Households,Ownership_Rented_Households,Type_of_bathing_facility_Enclosure_without_roof_Households,Type_of_fuel_used_for_cooking_Any_other_Households,Type_of_latrine_facility_Pit_latrine_Households,Type_of_latrine_facility_Other_latrine_Households,Type_of_latrine_facility_Night_soil_disposed_into_open_drain_Households,Type_of_latrine_facility_Flush_pour_flush_latrine_connected_to_other_system_Households,Not_having_bathing_facility_within_the_premises_Total_Households,Not_having_latrine_facility_within_the_premises_Alternative_source_Open_Households,Main_source_of_drinking_water_Un_covered_well_Households,Main_source_of_drinking_water_Handpump_Tubewell_Borewell_Households,Main_source_of_drinking_water_Spring_Households,Main_source_of_drinking_water_River_Canal_Households,Main_source_of_drinking_water_Other_sources_Households,Main_source_of_drinking_water_Other_sources_Spring_River_Canal_Tank_Pond_Lake_Other_sources__Households,Location_of_drinking_water_source_Near_the_premises_Households,Location_of_drinking_water_source_Within_the_premises_Households,Main_source_of_drinking_water_Tank_Pond_Lake_Households,Main_source_of_drinking_water_Tapwater_Households,Main_source_of_drinking_water_Tubewell_Borehole_Households,Household_size_1_person_Households,Household_size_2_persons_Households,Household_size_1_to_2_persons,Household_size_3_persons_Households,Household_size_3_to_5_persons_Households,Household_size_4_persons_Households,Household_size_5_persons_Households,Household_size_6_8_persons_Households,Household_size_9_persons_and_above_Households,Location_of_drinking_water_source_Away_Households,Married_couples_1_Households,Married_couples_2_Households,Married_couples_3_Households,Married_couples_3_or_more_Households,Married_couples_4_Households,Married_couples_5__Households,Married_couples_None_Households,Power_Parity_Less_than_Rs_45000,Power_Parity_Rs_45000_90000,Power_Parity_Rs_90000_150000,Power_Parity_Rs_45000_150000,Power_Parity_Rs_150000_240000,Power_Parity_Rs_240000_330000,Power_Parity_Rs_150000_330000,Power_Parity_Rs_330000_425000,Power_Parity_Rs_425000_545000,Power_Parity_Rs_330000_545000,Power_Parity_Above_Rs_545000,Total_Power_Parity
0,1,JAMMU & KASHMIR,Kupwara,870354,474190,396164,439654,282823,156831,1048,1046,2,70352,36913,33439,229064,190899,38165,123837,105227,641290,34680,56759,7946,129679,37128,823286,1700,5600,66,39,13,2522,15828,83071,762,5256,158438,23226,181664,60616,101642,99947,74948,39709,21751,6402,405015,289765,694780,600759,178435,89679,1481,3019,2988,59480,1808,1445,53437,495,26828,56495,1613,8463,104172,66361,54335,104807,618,3667,167,9791,21902,2269,10919,40416,44123,11127,5030,1902,24776,6597,34882,37849,22747,1607,50339,2066,911,4036,4947,6396,31982,10700,14886,42727,27121,46181,80569,14618,2218,2622,330,74,8968,259,494,94,588,71,101,172,74,10,84,15,1119
1,2,JAMMU & KASHMIR,Badgam,753745,398041,355704,335649,207741,127908,368,343,25,23912,12383,11529,214866,162578,52288,132003,82863,538879,55299,36630,29102,93835,10110,736054,1489,5559,47,6,2,478,15118,90190,1999,5892,160649,27190,187839,68336,80862,83141,66459,41367,27950,6857,374972,342646,717618,503223,160933,88978,611,10013,5091,66814,5848,2509,65783,1655,54170,72197,3905,3733,88806,83385,83615,98036,609,3959,971,7013,43953,1779,9208,15834,10642,699,9864,453,13064,1052,14705,33558,51358,136,73303,2321,845,2173,3018,3743,23640,7998,11899,59121,13440,14303,71441,15255,2962,3493,452,79,9030,201,436,126,562,72,89,161,96,28,124,18,1066
2,3,JAMMU & KASHMIR,Leh(Ladakh),133487,78971,54516,93770,62834,30936,488,444,44,95857,47543,48314,75079,53265,21814,57125,17954,58408,20869,1645,1020,51545,22882,19057,658,1092,88635,103,54,1006,13645,17250,574,2150,36920,17474,54394,10452,15181,17900,16265,8923,6197,575,75493,32637,108130,70703,41515,21019,250,609,4271,15210,1289,2646,6331,971,13597,13836,4859,371,20134,10304,18780,19387,893,920,1,14980,2117,53,695,10473,1781,64,5991,620,6115,1565,8355,10962,3031,55,6254,135,1630,1483,3113,2302,10528,4422,3804,5378,1758,6784,12742,3492,716,835,87,32,3708,33,76,46,122,15,22,37,20,14,34,17,242
3,4,JAMMU & KASHMIR,Kargil,140802,77785,63017,86236,56301,29935,18,12,6,122336,62652,59684,51873,39839,12034,28941,22932,88929,8266,3763,1222,38622,10341,108239,604,1171,20126,28,4,289,3285,15824,235,1005,40370,7774,48144,12732,19083,20874,16938,9826,3077,408,82938,39854,122792,87532,35561,17488,221,488,1847,10895,652,899,7733,249,8008,10562,1930,575,17751,11887,17649,16646,1419,330,376,1704,4732,37,9610,6325,482,1,3289,323,2641,907,4068,9218,1963,197,10769,19,689,834,1523,983,4991,1652,2356,6832,4866,7031,10366,3835,1252,1643,308,83,2368,39,87,27,114,12,18,30,19,3,22,7,214
4,5,JAMMU & KASHMIR,Punch,476835,251899,224936,261724,163333,98391,556,406,150,176101,90274,85827,161393,117677,43716,73247,88146,315442,54264,31583,3930,71616,32604,431279,958,11188,83,10,2,711,13160,62900,346,3342,132139,15269,147408,55762,72024,69219,46062,29517,13962,1884,288430,164044,452474,304979,109818,61334,704,846,1731,37412,2407,1908,31773,276,16022,36358,2677,2047,78572,19789,16586,87711,762,3421,28,532,971,338,1174,69089,70470,17702,4036,12448,1351,5351,19458,33146,17078,308,43697,234,1531,7435,8966,10664,44517,15825,18028,31443,3952,38654,70995,9180,1148,1250,87,15,7453,117,268,78,346,35,50,85,59,8,67,12,629

In [5]:
data.shape

(640, 118)

In [6]:
pd.options.display.max_info_columns=200

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 640 entries, 0 to 639
Data columns (total 118 columns):
District code                                                                                              640 non-null int64
State name                                                                                                 640 non-null object
District name                                                                                              640 non-null object
Population                                                                                                 640 non-null int64
Male                                                                                                       640 non-null int64
Female                                                                                                     640 non-null int64
Literate                                                                                                   640 non-null int64
Male_Literate                                                                                              640 non-null int64
Female_Literate                                                                                            640 non-null int64
SC                                                                                                         640 non-null int64
Male_SC                                                                                                    640 non-null int64
Female_SC                                                                                                  640 non-null int64
ST                                                                                                         640 non-null int64
Male_ST                                                                                                    640 non-null int64
Female_ST                                                                                                  640 non-null int64
Workers                                                                                                    640 non-null int64
Male_Workers                                                                                               640 non-null int64
Female_Workers                                                                                             640 non-null int64
Main_Workers                                                                                               640 non-null int64
Marginal_Workers                                                                                           640 non-null int64
Non_Workers                                                                                                640 non-null int64
Cultivator_Workers                                                                                         640 non-null int64
Agricultural_Workers                                                                                       640 non-null int64
Household_Workers                                                                                          640 non-null int64
Other_Workers                                                                                              640 non-null int64
Hindus                                                                                                     640 non-null int64
Muslims                                                                                                    640 non-null int64
Christians                                                                                                 640 non-null int64
Sikhs                                                                                                      640 non-null int64
Buddhists                                                                                                  640 non-null int64
Jains                                                                                                      640 non-null int64
Others_Religions                                                                                           640 non-null int64
Religion_Not_Stated                                                                                        640 non-null int64
LPG_or_PNG_Households                                                                                      640 non-null int64
Housholds_with_Electric_Lighting                                                                           640 non-null int64
Households_with_Internet                                                                                   640 non-null int64
Households_with_Computer                                                                                   640 non-null int64
Rural_Households                                                                                           640 non-null int64
Urban_Households                                                                                           640 non-null int64
Households                                                                                                 640 non-null int64
Below_Primary_Education                                                                                    640 non-null int64
Primary_Education                                                                                          640 non-null int64
Middle_Education                                                                                           640 non-null int64
Secondary_Education                                                                                        640 non-null int64
Higher_Education                                                                                           640 non-null int64
Graduate_Education                                                                                         640 non-null int64
Other_Education                                                                                            640 non-null int64
Literate_Education                                                                                         640 non-null int64
Illiterate_Education                                                                                       640 non-null int64
Total_Education                                                                                            640 non-null int64
Age_Group_0_29                                                                                             640 non-null int64
Age_Group_30_49                                                                                            640 non-null int64
Age_Group_50                                                                                               640 non-null int64
Age not stated                                                                                             640 non-null int64
Households_with_Bicycle                                                                                    640 non-null int64
Households_with_Car_Jeep_Van                                                                               640 non-null int64
Households_with_Radio_Transistor                                                                           640 non-null int64
Households_with_Scooter_Motorcycle_Moped                                                                   640 non-null int64
Households_with_Telephone_Mobile_Phone_Landline_only                                                       640 non-null int64
Households_with_Telephone_Mobile_Phone_Mobile_only                                                         640 non-null int64
Households_with_TV_Computer_Laptop_Telephone_mobile_phone_and_Scooter_Car                                  640 non-null int64
Households_with_Television                                                                                 640 non-null int64
Households_with_Telephone_Mobile_Phone                                                                     640 non-null int64
Households_with_Telephone_Mobile_Phone_Both                                                                640 non-null int64
Condition_of_occupied_census_houses_Dilapidated_Households                                                 640 non-null int64
Households_with_separate_kitchen_Cooking_inside_house                                                      640 non-null int64
Having_bathing_facility_Total_Households                                                                   640 non-null int64
Having_latrine_facility_within_the_premises_Total_Households                                               640 non-null int64
Ownership_Owned_Households                                                                                 640 non-null int64
Ownership_Rented_Households                                                                                640 non-null int64
Type_of_bathing_facility_Enclosure_without_roof_Households                                                 640 non-null int64
Type_of_fuel_used_for_cooking_Any_other_Households                                                         640 non-null int64
Type_of_latrine_facility_Pit_latrine_Households                                                            640 non-null int64
Type_of_latrine_facility_Other_latrine_Households                                                          640 non-null int64
Type_of_latrine_facility_Night_soil_disposed_into_open_drain_Households                                    640 non-null int64
Type_of_latrine_facility_Flush_pour_flush_latrine_connected_to_other_system_Households                     640 non-null int64
Not_having_bathing_facility_within_the_premises_Total_Households                                           640 non-null int64
Not_having_latrine_facility_within_the_premises_Alternative_source_Open_Households                         640 non-null int64
Main_source_of_drinking_water_Un_covered_well_Households                                                   640 non-null int64
Main_source_of_drinking_water_Handpump_Tubewell_Borewell_Households                                        640 non-null int64
Main_source_of_drinking_water_Spring_Households                                                            640 non-null int64
Main_source_of_drinking_water_River_Canal_Households                                                       640 non-null int64
Main_source_of_drinking_water_Other_sources_Households                                                     640 non-null int64
Main_source_of_drinking_water_Other_sources_Spring_River_Canal_Tank_Pond_Lake_Other_sources__Households    640 non-null int64
Location_of_drinking_water_source_Near_the_premises_Households                                             640 non-null int64
Location_of_drinking_water_source_Within_the_premises_Households                                           640 non-null int64
Main_source_of_drinking_water_Tank_Pond_Lake_Households                                                    640 non-null int64
Main_source_of_drinking_water_Tapwater_Households                                                          640 non-null int64
Main_source_of_drinking_water_Tubewell_Borehole_Households                                                 640 non-null int64
Household_size_1_person_Households                                                                         640 non-null int64
Household_size_2_persons_Households                                                                        640 non-null int64
Household_size_1_to_2_persons                                                                              640 non-null int64
Household_size_3_persons_Households                                                                        640 non-null int64
Household_size_3_to_5_persons_Households                                                                   640 non-null int64
Household_size_4_persons_Households                                                                        640 non-null int64
Household_size_5_persons_Households                                                                        640 non-null int64
Household_size_6_8_persons_Households                                                                      640 non-null int64
Household_size_9_persons_and_above_Households                                                              640 non-null int64
Location_of_drinking_water_source_Away_Households                                                          640 non-null int64
Married_couples_1_Households                                                                               640 non-null int64
Married_couples_2_Households                                                                               640 non-null int64
Married_couples_3_Households                                                                               640 non-null int64
Married_couples_3_or_more_Households                                                                       640 non-null int64
Married_couples_4_Households                                                                               640 non-null int64
Married_couples_5__Households                                                                              640 non-null int64
Married_couples_None_Households                                                                            640 non-null int64
Power_Parity_Less_than_Rs_45000                                                                            640 non-null int64
Power_Parity_Rs_45000_90000                                                                                640 non-null int64
Power_Parity_Rs_90000_150000                                                                               640 non-null int64
Power_Parity_Rs_45000_150000                                                                               640 non-null int64
Power_Parity_Rs_150000_240000                                                                              640 non-null int64
Power_Parity_Rs_240000_330000                                                                              640 non-null int64
Power_Parity_Rs_150000_330000                                                                              640 non-null int64
Power_Parity_Rs_330000_425000                                                                              640 non-null int64
Power_Parity_Rs_425000_545000                                                                              640 non-null int64
Power_Parity_Rs_330000_545000                                                                              640 non-null int64
Power_Parity_Above_Rs_545000                                                                               640 non-null int64
Total_Power_Parity                                                                                         640 non-null int64
dtypes: int64(116), object(2)
memory usage: 590.1+ KB

In [8]:
cat_data=data.select_dtypes(include='object')
num_data=data.select_dtypes(exclude='object')

print(cat_data.shape)
print(num_data.shape)

(640, 2)
(640, 116)

In [9]:
cat_data.head()

        State name District name
0  JAMMU & KASHMIR       Kupwara
1  JAMMU & KASHMIR        Badgam
2  JAMMU & KASHMIR   Leh(Ladakh)
3  JAMMU & KASHMIR        Kargil
4  JAMMU & KASHMIR         Punch

In [10]:
from sklearn.cluster import KMeans

In [ ]:
kmeans = KMeans(n_clusters=3)
kmeans.fit(num_data)
pred = kmeans.predict(num_data)

In [12]:
kmeans.cluster_centers_

array([[3.93647059e+02, 7.47131129e+06, 3.89886000e+06, 3.57245129e+06,
        5.31786894e+06, 2.96160876e+06, 2.35626018e+06, 1.12761976e+06,
        5.79232824e+05, 5.48386941e+05, 4.41861471e+05, 2.23462000e+05,
        2.18399471e+05, 2.92879994e+06, 2.19806671e+06, 7.30733235e+05,
        2.43193147e+06, 4.96868471e+05, 4.54251135e+06, 3.83950941e+05,
        5.21504941e+05, 1.34605353e+05, 1.88873871e+06, 5.80308541e+06,
        1.36105941e+06, 9.90824118e+04, 1.33585882e+04, 8.23440000e+04,
        6.99858235e+04, 2.02036471e+04, 2.21920000e+04, 7.30630941e+05,
        1.22776218e+06, 1.20292706e+05, 2.68466118e+05, 8.60979235e+05,
        1.31733712e+06, 2.17831635e+06, 7.62203824e+05, 1.28779924e+06,
        1.23633029e+06, 9.66181176e+05, 5.84955941e+05, 6.62287706e+05,
        9.11637647e+04, 5.59092194e+06, 1.69120418e+06, 7.28212612e+06,
        4.20862235e+06, 2.07151806e+06, 1.16374976e+06, 2.74211176e+04,
        6.46935706e+05, 1.21361765e+05, 4.19192706e+05, 4.03502882e+05,
        7.79390588e+04, 9.18614294e+05, 1.52142647e+05, 9.33224824e+05,
        1.13894753e+06, 1.42394176e+05, 9.19704118e+04, 1.46241724e+06,
        1.08102241e+06, 1.06399059e+06, 1.22361024e+06, 3.21263176e+05,
        1.46104706e+05, 1.41237647e+04, 2.30580118e+05, 1.73030000e+04,
        9.00411765e+03, 4.02831765e+04, 5.07522059e+05, 3.93975588e+05,
        6.59838824e+04, 5.68824412e+05, 1.72235294e+03, 2.93623529e+03,
        1.92213529e+04, 3.02911765e+04, 4.15270235e+05, 9.24510765e+05,
        6.41123529e+03, 9.11410235e+05, 1.73435235e+05, 5.59700588e+04,
        1.55743647e+05, 2.11713706e+05, 2.72459235e+05, 9.75065765e+05,
        4.14396588e+05, 2.88209941e+05, 3.18799235e+05, 8.29657647e+04,
        2.48763471e+05, 1.12257529e+06, 2.07997353e+05, 4.70669412e+04,
        5.90676471e+04, 9.21211765e+03, 2.78858824e+03, 1.98904176e+05,
        1.08894118e+03, 3.26152941e+03, 3.94776471e+03, 7.20929412e+03,
        1.67200000e+03, 1.15123529e+03, 2.82323529e+03, 1.16894118e+03,
        1.67805882e+03, 2.84700000e+03, 2.00035294e+03, 1.59688235e+04],
       [3.03209302e+02, 1.05551413e+06, 5.43429053e+05, 5.12085081e+05,
        6.50682998e+05, 3.73875112e+05, 2.76807886e+05, 1.68107872e+05,
        8.67658814e+04, 8.13419907e+04, 1.56420553e+05, 7.84458512e+04,
        7.79747023e+04, 4.36069970e+05, 2.90190088e+05, 1.45879881e+05,
        3.15537016e+05, 1.20532953e+05, 6.19444165e+05, 1.34534751e+05,
        1.30960070e+05, 1.36863419e+04, 1.56933363e+05, 8.33918898e+05,
        1.27378851e+05, 3.80081488e+04, 3.22779442e+04, 7.40669070e+03,
        2.96899070e+03, 1.16821070e+04, 1.87250465e+03, 4.84791349e+04,
        1.40732849e+05, 4.25599767e+03, 1.59337698e+04, 2.19466498e+05,
        7.34382233e+04, 2.92904721e+05, 1.33205160e+05, 1.81521888e+05,
        1.39763470e+05, 1.08198681e+05, 6.60831395e+04, 5.07827442e+04,
        8.30367674e+03, 6.87858760e+05, 3.43839288e+05, 1.03169805e+06,
        6.22614386e+05, 2.65797398e+05, 1.65008316e+05, 2.09403488e+03,
        9.14207047e+04, 9.17854186e+03, 3.79327791e+04, 4.13481628e+04,
        7.53257442e+03, 1.06337170e+05, 7.23052093e+03, 9.16009279e+04,
        1.24889374e+05, 1.10196302e+04, 1.08526442e+04, 1.89580335e+05,
        1.14311984e+05, 9.00375953e+04, 1.90127158e+05, 1.77673767e+04,
        3.42944907e+04, 6.44974419e+02, 2.25745233e+04, 2.22183023e+03,
        1.02710930e+03, 5.26835814e+03, 9.91959907e+04, 1.18714295e+05,
        2.64340930e+04, 9.04669349e+04, 2.35210698e+03, 2.54667674e+03,
        3.06989767e+03, 1.07331628e+04, 8.31574953e+04, 8.47223070e+04,
        2.76448140e+03, 8.19358814e+04, 1.84279047e+04, 8.02404186e+03,
        2.02029907e+04, 2.82270326e+04, 2.73975093e+04, 1.14874084e+05,
        4.59992000e+04, 4.14773744e+04, 5.68826419e+04, 1.35242163e+04,
        4.56281721e+04, 1.49651207e+05, 3.04702186e+04, 6.56094884e+03,
        8.24341163e+03, 1.30365349e+03, 3.78809302e+02, 2.51431372e+04,
        2.25865116e+02, 5.40988372e+02, 4.48548837e+02, 9.89537209e+02,
        1.75751163e+02, 1.27504651e+02, 3.03255814e+02, 1.16048837e+02,
        1.57483721e+02, 2.73532558e+02, 1.57495349e+02, 1.94965814e+03],
       [3.52580311e+02, 3.26410159e+06, 1.67520801e+06, 1.58889359e+06,
        2.03855622e+06, 1.15880816e+06, 8.79748062e+05, 5.69546378e+05,
        2.92119311e+05, 2.77427067e+05, 1.54265456e+05, 7.78064508e+04,
        7.64590052e+04, 1.26730146e+06, 8.79746130e+05, 3.87555332e+05,
        9.61356575e+05, 3.05944886e+05, 1.99680013e+06, 2.82029383e+05,
        4.10230233e+05, 5.26670984e+04, 5.22374746e+05, 2.63740816e+06,
        4.88778456e+05, 5.07341088e+04, 3.48523523e+04, 1.99909171e+04,
        1.02866736e+04, 1.33210674e+04, 8.72985492e+03, 1.92518803e+05,
        4.37876746e+05, 1.98625181e+04, 6.19036321e+04, 5.78697788e+05,
        2.91019098e+05, 8.69716886e+05, 4.22983938e+05, 5.49223782e+05,
        4.47454990e+05, 3.53971233e+05, 2.13010881e+05, 1.90015326e+05,
        2.68469793e+04, 2.20350713e+06, 1.00390067e+06, 3.20740780e+06,
        1.89916055e+06, 8.23748114e+05, 5.25010503e+05, 1.61824249e+04,
        3.12220845e+05, 2.83091399e+04, 1.32534839e+05, 1.41051725e+05,
        2.77495855e+04, 3.61971995e+05, 2.96107202e+04, 3.17307788e+05,
        4.29100052e+05, 3.93784715e+04, 3.61258394e+04, 5.64931083e+05,
        3.96872409e+05, 3.05354674e+05, 5.74975290e+05, 7.39215440e+04,
        1.20299373e+05, 3.51614508e+03, 5.00115078e+04, 7.02974093e+03,
        3.73018135e+03, 1.38423212e+04, 2.65712990e+05, 3.37890041e+05,
        5.59662228e+04, 2.84688124e+05, 1.41901554e+03, 2.10135751e+03,
        1.03497668e+04, 1.78984456e+04, 2.36234098e+05, 3.25251554e+05,
        4.02830570e+03, 2.93682762e+05, 5.20397720e+04, 2.40487772e+04,
        6.55333368e+04, 8.95821140e+04, 8.93729845e+04, 3.62334290e+05,
        1.51052819e+05, 1.21908487e+05, 1.63341202e+05, 4.73277927e+04,
        1.01099746e+05, 4.63891383e+05, 9.44971813e+04, 2.22309896e+04,
        2.93266010e+04, 5.23564767e+03, 1.85996373e+03, 7.48702332e+04,
        6.43072539e+02, 1.52637824e+03, 1.25949223e+03, 2.78587047e+03,
        4.36077720e+02, 3.28466321e+02, 7.64544041e+02, 2.82476684e+02,
        3.67626943e+02, 6.50103627e+02, 4.00181347e+02, 5.24373575e+03]])

In [14]:
from sklearn.metrics import pairwise_distances

In [16]:
pairwise_distances(num_data)

array([[      0.        ,  297411.90496683, 1726633.72587066, ...,
        1911786.20064719, 1768297.34032345, 1510393.49234297],
       [ 297411.90496683,       0.        , 1529744.61412224, ...,
        1709086.56686986, 1566360.72088679, 1315373.54640878],
       [1726633.72587066, 1529744.61412224,       0.        , ...,
         255256.32637997,  183201.73941587,  370190.35649514],
       ...,
       [1911786.20064719, 1709086.56686986,  255256.32637997, ...,
              0.        ,  188430.68209822,  528871.8202977 ],
       [1768297.34032345, 1566360.72088679,  183201.73941587, ...,
         188430.68209822,       0.        ,  350760.34942821],
       [1510393.49234297, 1315373.54640878,  370190.35649514, ...,
         528871.8202977 ,  350760.34942821,       0.        ]])