In [1]:
import pandas as pd
import numpy as np

In [4]:
data1= pd.read_csv('D:\\Datasets\\AVH- Innoplexus\\information_train.csv',sep='\t',parse_dates=True)
data1.head()

,abstract,article_title,author_str,pmid,pub_date,set,full_Text
0,"Among bioethicists and members of the public, ...",The routinisation of genomics and genetics: im...,"M W Foster, C D M Royal, R R Sharp",17074820,2006-11-01,13,NaN
1,Genomics resources that use samples from ident...,Integrating ethics and science in the Internat...,NaN,15153999,2008-02-25,13,NaN
2,Alleviating health disparities in the United S...,Genetic Research and Health Disparities,"Pamela Sankar, Mildred K. Cho, Celeste M. Cond...",15213210,2008-02-20,13,NaN
3,Protecting the confidentiality of genetic rese...,Certificates of confidentiality: a valuable to...,"C L Earley, L C Strong",7668302,1995-09-01,13,NaN
4,Whereas the human linkage map appears on limit...,Linkage disequilibrium in human populations,"Christine Lonjou, Weihua Zhang, Andrew Collins...",12721363,2003-05-13,13,NaN

In [6]:
train = pd.read_csv('D:\\Datasets\\AVH- Innoplexus\\train.csv')
train.head()

       pmid                                           ref_list
0  17074820                ['15153999', '15213210', '7668302']
1  15153999  ['12721363', '9096352', '10788337', '9114021',...
2  15213210                           ['11466240', '12184798']
3   7668302                                        ['1539589']
4  12721363  ['9465087', '11842208', '11309498', '9465125',...

In [8]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3522 entries, 0 to 3521
Data columns (total 2 columns):
pmid        3522 non-null int64
ref_list    3522 non-null object
dtypes: int64(1), object(1)
memory usage: 55.1+ KB

In [9]:
data1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3522 entries, 0 to 3521
Data columns (total 7 columns):
abstract         3522 non-null object
article_title    3522 non-null object
author_str       3089 non-null object
pmid             3522 non-null int64
pub_date         3522 non-null object
set              3522 non-null int64
full_Text        141 non-null object
dtypes: int64(2), object(5)
memory usage: 192.7+ KB

In [15]:
data1['article_title']

0       The routinisation of genomics and genetics: im...
1       Integrating ethics and science in the Internat...
2                 Genetic Research and Health Disparities
3       Certificates of confidentiality: a valuable to...
4             Linkage disequilibrium in human populations
5       Microsatellite diversity and the demographic h...
6       Haplotypes and linkage disequilibrium at the p...
7                 An apportionment of human DNAâ€‰diversity
8       The role of community review in evaluating the...
9       Inflation of sibling recurrence-risk ratio, du...
10      Blindness in Africa: present situation and fut...
11      Categorization of humans in biomedical researc...
12      Genetic epidemiology, genetic maps and positio...
13                              Minimal haplotype tagging
14      Discrimination as a consequence of genetic tes...
15         Mapping a disease locus by allelicâ€‰association
16      The first linkage disequilibrium (LD) maps: De...
17             The optimal measure of allelic association
18                   Genetic traces of ancientâ€‰demography
19                Allelic association between marker loci
20         Properties of linkage disequilibrium (LD) maps
21      Allele Frequencies at Microsatellite Loci: The...
22      Mutation rate varies among alleles at a micros...
23      Nonneutral Mitochondrial DNA Variation in Huma...
24      Microsatellite variability and genetic distances.
25      Ascertainment bias in estimates of average het...
26      Origins and affinities of modern humans: a com...
27      Population genetics of dinucleotide (dC-dA)n.(...
28      Mutational processes of simple-sequence repeat...
29      Phenylalanine hydroxylase gene haplotypes in P...
                              ...
3492    MORPHOLOGY AND PEROXIDASE CYTOCHEMISTRY OF MOU...
3493    The Hemolysis of Red Cells from Patients with ...
3494    Ultrastructural localization of the third and ...
3495    The ninth component of human complement: isola...
3496    PASSIVE HEMOLYSIS BY SERUM AND COBRA VENOM FAC...
3497    THE EIGHTH COMPONENT OF HUMAN COMPLEMENT (C8):...
3498    REACTIVE LYSIS: THE COMPLEMENT-MEDIATED LYSIS ...
3499    THE REACTION MECHANISM OF HUMAN C5 IN IMMUNE H...
3500    FLUID PHASE DESTRUCTION OF C2hu BY C1hu II. UN...
3501    Studies in vivo and in vitro on an abnormality...
3502    MODULATION OF FUNCTION OF THE ACTIVATED FIRST ...
3503    Studies of the In Vivo Behavior of Human Câ€²3 i...
3504    REACTIVE LYSIS: THE COMPLEMENT-MEDIATED LYSIS ...
3505    STUDIES ON THE ANTIGENIC PROPERTIES OF COMPLEM...
3506    THE INTERACTION OF MYCOPLASMAS WITH MAMMALIAN ...
3507    STUDIES ON HUMAN PERIPHERAL BLOOD LYMPHOCYTES ...
3508    LYSOSOMES IN LYMPHOID TISSUE II. Intracellular...
3509    LYSOSOMES IN LYMPHOID TISSUE III. Influence of...
3510    ACID PHOSPHATASE LOCALIZATION IN RABBIT EOSINO...
3511    STUDIES ON LYSOSOMES IV. Solubilization of Enz...
3512    STUDIES ON LYSOSOMES V. The Effects of Strepto...
3513    Multiple nature of the third component of guin...
3514    The preparation and properties of alexinated i...
3515    Antibody responses to bacteriaThe effect of th...
3516    MECHANISMS OF IMMUNOLOGIC INJURY OF RAT PERITO...
3517    MECHANISMS OF IMMUNOLOGIC INJURY OF RAT PERITO...
3518    MECHANISMS OF THE INHIBITION OF CHEMOTAXIS BY ...
3519                      CHEMOTAXIS OF MONONUCLEAR CELLS
3520    Effect of Chloroquine on Morphology of Cytopla...
3521    LYSOSOMAL AND ULTRASTRUCTURAL CHANGES IN HUMAN...
Name: article_title, Length: 3522, dtype: object

In [17]:
final=pd.merge(data,data1,on='pmid')
final.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3522 entries, 0 to 3521
Data columns (total 8 columns):
pmid             3522 non-null int64
ref_list         3522 non-null object
abstract         3522 non-null object
article_title    3522 non-null object
author_str       3089 non-null object
pub_date         3522 non-null object
set              3522 non-null int64
full_Text        141 non-null object
dtypes: int64(2), object(6)
memory usage: 247.6+ KB

In [18]:
final.head()

,pmid,ref_list,abstract,article_title,author_str,pub_date,set,full_Text
0,17074820,"['15153999', '15213210', '7668302']","Among bioethicists and members of the public, ...",The routinisation of genomics and genetics: im...,"M W Foster, C D M Royal, R R Sharp",2006-11-01,13,NaN
1,15153999,"['12721363', '9096352', '10788337', '9114021',...",Genomics resources that use samples from ident...,Integrating ethics and science in the Internat...,NaN,2008-02-25,13,NaN
2,15213210,"['11466240', '12184798']",Alleviating health disparities in the United S...,Genetic Research and Health Disparities,"Pamela Sankar, Mildred K. Cho, Celeste M. Cond...",2008-02-20,13,NaN
3,7668302,['1539589'],Protecting the confidentiality of genetic rese...,Certificates of confidentiality: a valuable to...,"C L Earley, L C Strong",1995-09-01,13,NaN
4,12721363,"['9465087', '11842208', '11309498', '9465125',...",Whereas the human linkage map appears on limit...,Linkage disequilibrium in human populations,"Christine Lonjou, Weihua Zhang, Andrew Collins...",2003-05-13,13,NaN